version: '3.8'

services:
  certbot:
    container_name: cmsapp-web-certbot
    build: ./services/certbot
    command: certonly -d jumpifzer0.me --email jumpifzer0@protonmail.com --agree-tos --standalone
    image: certbot/certbot:latest
    depends_on:
      - web
    networks:
      - frontend
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  nginx:
    container_name: cmsapp-proxy
    build: ./services/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot
    networks:
      - frontend
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  web:
    container_name: cmsapp-web
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:32984 manage:app
    expose:
      - 32984
    env_file:
      - ./.web.prod.env
    depends_on:
      - db
    networks:
      - frontend
      - backend
  db:
    container_name: cmsapp-db
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.db.prod.env
    networks:
      - backend


networks:
  frontend:
  backend:

volumes:
  postgres_data:
