version: '3.8'

services:
  nginx:
    container_name: cmsapp-proxy
    build: ./services/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - frontend
  web:
    container_name: cmsapp-web
    build: ./services/web
    command: gunicorn -w 3 --bind 0.0.0.0:32984 manage:app
    expose:
      - 32984
    env_file:
      - ./.web.prod.env
    # environment:
    #   # CMS
    #   - FLASK_APP=${FLASK_APP}
    #   - FLASK_DEBUG=${FLASK_DEBUG}
    #   - CMS_DEBUG=${CMS_DEBUG}
    #   - SECRET_KEY=${SECRET_KEY}
    #   - ASSETS_ROOT=${ASSETS_ROOT}
    #   # DB
    #   - DB_ENGINE=${DB_ENGINE}
    #   - DB_USERNAME=${DB_USERNAME}
    #   - DB_PASS=${DB_PASS}
    #   - DB_HOST=${DB_HOST}
    #   - DB_PORT=${DB_PORT}
    #   - DB_NAME=${DB_NAME}
    #   # MX
    #   - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY}
    #   - GENERATE_TOKEN_SALT=${GENERATE_TOKEN_SALT}
    #   - APP_MAIL_USERNAME=${APP_MAIL_USERNAME}
    #   - APP_MAIL_PASSWORD=${APP_MAIL_PASSWORD}
    #   - MAIL_SERVER=${MAIL_SERVER}
    #   - MAIL_PORT=${MAIL_PORT}
    #   - MAIL_USE_TLS=${MAIL_USE_TLS}
    #   - MAIL_USE_SSL=${MAIL_USE_SSL}
    depends_on:
      - db
    networks:
      - frontend
      - backend
  db:
    container_name: cmsapp-db
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.db.prod.env
    # environment:
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  postgres_data: