version: '3.8'

services:
  nginx:
    container_name: cmsapp-proxy
    build: ./services/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - frontend
    volumes:
      - ./services/nginx/certs/:/etc/ssl/certs/
      - ./services/nginx/ssl/private/:/etc/ssl/private/
  web:
    container_name: cmsapp-web
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:32984 manage:app
    expose:
      - 32984
    env_file:
      - ./.web.prod.env
    depends_on:
      - db
    networks:
      - frontend
      - backend
  db:
    container_name: cmsapp-db
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.db.prod.env
    networks:
      - backend


networks:
  frontend:
  backend:

volumes:
  postgres_data:
