FROM certbot/certbot:latest

#RUN docker compose run --rm  certbot certonly --webroot --webroot-path /var/www/certbot/ --dry-run -d jumpifzer0.me

# this is an input when CMD asks for email address
#RUN echo test@test.com   

# this is an input when CMD asks to accept T0S
#RUN echo Y